- name: Install container and terminal tools
  dnf:
    name:
      - docker
      - docker-compose
      - podman-compose
      - podman 
      - distrobox
      - alacritty
      - zsh
      - lm_sensors
      - mpv 
      - firewalld
      - zsh-autosuggestion
      - zsh-syntax-highlighting
    state: present

- name: Enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_facts.user_id }}"
    groups: docker
    append: true

