- name: Ensure Flathub exists
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps
  flatpak:
    name:
      - com.spotify.Client
      - app.zen_browser.zen 
      - it.mijorus.gearlever
    state: present

