add_newline = false

format = """
$username@$hostname \
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$rust\
$golang\
$python\
$nodejs\
$java\
$terraform\
$character
"""

# -----------------------
# USERNAME
# -----------------------
[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)"

# -----------------------
# HOSTNAME
# -----------------------
[hostname]
ssh_only = false
style = "bold dimmed white"
format = "[$hostname]($style)"

# -----------------------
# DIRECTORY
# -----------------------
[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"

# -----------------------
# GIT
# -----------------------
[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_status]
style = "red"

# -----------------------
# LANGUAGES
# -----------------------

# C
[c]
symbol = "î˜ "
style = "blue"
format = "[$symbol$version]($style) "

# C++
[cpp]
symbol = "î˜ "
style = "blue"
format = "[$symbol$version]($style) "

# Rust
[rust]
symbol = "ğŸ¦€ "
style = "red"
format = "[$symbol$version]($style) "

# Go
[golang]
symbol = "î˜§ "
style = "cyan"
format = "[$symbol$version]($style) "

# Python
[python]
symbol = "ğŸ "
style = "yellow"
format = "[$symbol$version]($style) "

# Node
[nodejs]
symbol = "â¬¢ "
style = "green"
format = "[$symbol$version]($style) "

# Java
[java]
symbol = "â˜• "
style = "red"
format = "[$symbol$version]($style) "

# Terraform
[terraform]
symbol = "ğŸ’  "
style = "magenta"
format = "[$symbol$version]($style) "

# -----------------------
# PROMPT SYMBOL
# -----------------------
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

